const exhibitions = [
  'Edvard Munch. Thema und Variation',
  'Das Auge und der Apparat. Eine Geschichte der Fotografie',
  'Brassaï',
  'Florentina Pakosta',
  'Georg Baselitz. Die monumentalen Aquarelle',
  'Albrecht Dürer',
  'Günter Brus. Werkumkreisung',
  'Gustav Klimt bis Paul Klee. Wotruba und die Moderne',
  'Pop Art & Minimalismus. The Serial Attitude',
  'Rembrandt',
  'Michelangelo und seine Zeit. Meisterwerke der Albertina',
  'Peter Paul Rubens',
  'Neo Rauch, Arbeiten auf Papier 2003–2004',
  'Chagall. Die Mythen der Bibel',
  'Alex Katz. Kartons und Gemälde',
  'Piet Mondrian',
  'Goya bis Picasso',
  'Joseph von Führich. Die Kartons zum Wiener Kreuzweg',
  'Rudolf von Alt 1812–1905',
  'Jannis Kounellis. OPUS 1',
  'Stadt.Leben.Wien',
  'Egon Schiele',
  'MOZART. Experiment Aufklärung',
  'Pioniere der Daguerreotypie in Österreich',
  'Picasso – Malen gegen die Zeit',
  'Franz Gertsch: Holzschnitte und Gemälde 1986–2006',
  'Andy Warhol: POPSTARS. Zeichnungen und Collagen',
  'BASELITZ Remix',
  'Biedermeier – Die Erfindung der Einfachheit',
  'Peter Fendi und sein Kreis',
  'Blicke, Passanten – 1930 bis heute. Aus der Fotosammlung der Albertina',
  'Expressiv! Die Künstler der Brücke. Die Sammlung Hermann Gerlinger',
  'Desert Dreaming: Australian Aboriginal Art',
  'Philip Guston. Arbeiten auf Papier',
  'Monet bis Picasso – Die Sammlung Batliner',
  'Ausstellung der Ö1-Grafiken 2007 in der Albertina',
  'Kunst nach 1970. Aus der Albertina',
  'Der Mnemosyne-Atlas von Aby Warburg',
  'Karel Appel. Monumentale Aktzeichnungen',
  'Max Ernst: Une semaine de bonté. Die Originalcollagen',
  'Oskar Kokoschka. Exil und neue Heimat 1834–1980',
  'Paul Klee – FormenSpiele',
  'Die Weite des Eises. Arktis und Alpen 1860 bis heute',
  'Van Gogh – gezeichnete Bilder',
  'Nach 1970. Österreichische Kunst aus der Albertina',
  'Wege der Moderne. Aus der Sammlung Eberhard W. Kornfeld',
  'Gerhard Richter. Bilder aus privaten Sammlungen',
  'Fotografie und das Unsichtbare. 1840–1900',
  'Das Zeitalter Rembrandts',
  'Impressionismus. Wie das Licht auf die Leinwand kam',
  'Am Horizont der Sinne – Am Horizont der Dinge. Gemeinschaftsarbeiten Günter Brus – Arnulf Rainer',
  'Andy Warhol. Cars',
  'Jakob und Rudolf von Alt',
  'Monet bis Baselitz',
  'Markus Lüpertz',
  'Alex Katz. Prints',
  'Heinrich Kühn',
  'Walton Ford',
  'Picasso',
  'Michelangelo',
  'Herbert Brandl',
  'William Kentridge',
  'Roy Lichtenstein',
  'Der Blaue Reiter',
  'Mel Ramos',
  'Max Weiler',
  'Die Explosion der Bilderwelt',
  'Albertina Contemporary',
  'Zwischentöne – die Sammlung Forberg',
  'Magritte',
  'Surrealismus',
  'Impressionismus',
  'Gustav Klimt. Die Zeichnungen',
  'Albertina Contemporary',
  'Kirchner Heckel Nolde',
  'Joel Sternfeld',
  'Körper als Protest',
  'Kaiser Maximilian I. und die Kunst der Dürer-Zeit',
  'Markus Hofer',
  'Albertina Contemporary',
  'Erwin Wurm',
  'Max Ernst',
  'Lewis Baltz',
  'Antoine Roegiers',
  'Bosch Bruegel Rubens Rembrandt',
  'Gottfried Helnwein',
  'Gunter Damisch',
  'Albertina Contemporary',
  'Dreaming Russia',
  'Marianne Lang',
  'Matisse und die Fauves',
  'Sonja Gangl',
  'Georg Baselitz',
  'Eric Fischl',
  'Dürer, Michelangelo, Rubens',
  'Blow-Up',
  'Alex Katz. Zeichnungen, Kartons, Gemälde',
  'Arnulf Rainer',
  'Miro',
  'Karl Prantl',
  'Birgit Graschopf',
  'Degas, Cezanne, Seurat',
  'Warhol bis Richter',
  'Sturtevant',
  'Von der Schönheit der Natur',
  'Lee Miller',
  'Bacon, Warhol, Richter',
  'Abstraktion in Österreich',
  'Black & White',
  'Lyonel Feininger und Alfred Kubin',
  'Edvard Munch',
  'Drawing Now: 2015',
  'Spurensuche',
  'Welten der Romantik',
  'Hans Robert Pippal',
  'Provoke',
  'Chagall bis Malewitsch',
  'Anselm Kiefer',
  'Erwin Bohatsch',
  'Spatial Dispositions. Aldo Giannotti',
  'Land & Leute',
  'Albertina Contemporary',
  'Jim Dine. I Never Look Away',
  'Seurat, Signac, Van Gogh. Wege des Pointillismus',
  'Der Farbholzschnitt in Wien um 1900',
  'Film-Stills',
  'Markus Prachensky',
  'Von Poussin bis David',
  'Egon Schiele',
  'Acting for the camera',
  'Eduard Angeli',
  'Maria Lassnig – Zwiegespräche',
  'Österreichische Fotografie nach 1970',
  'Burhan Dogancay',
  'LOOK! New Acquisitions / Neuerwerbungen',
  'Pieter Bruegel der Ältere',
  'Raffael',
  'Contemporary Art. Die Sammlung Batliner',
  'Robert Frank',
  'Meisterwerke der Architekturzeichnung',
  'Max Weiler. Die Schenkung',
  'Das Wiener Aquarell',
  'Martha Jungwirth',
  'The Director’s Choice – Meisterwerke der Fotosammlung',
  'Keith Haring. The Alphabet',
  'Florentina Pakosta',
  'Alfred Seiland',
  'Meisterwerke der Architekturzeichnung Teil II',
  'Contemporary Art – Kunstwerke der zweiten Hälfte des 20. Jahrhunderts bis heute – Warhol bis Richter',
  'Claude Monet',
  'Helen Levitt',
  'Niko Pirosmani',
  'Erwin Wurm. Peace & Plenty',
  'Walter Schmögner. Skulpturen & Objekte',
  'Manfred Willmann',
  'Rubens bis Makart.',
  'Rudolf von Alt und seine Zeit. Aquarelle aus den Fürstlichen Sammlungen Liechtenstein.',
  'Die Neue Sachlichkeit',
  'Monet bis Picasso - Die Sammlung Batliner',
  'Hermann Nitsch',
  'Foto.Buch.Kunst',
  'Sean Scully Eleuthera',
  'Maria Lassnig',
  'Albrecht Dürer',
  'Arnulf Rainer',
  'A Passion for Drawing',
  'Warhol bis Richter.',
  'Wilhelm Leibl',
  'Die frühe Radierung',
  'Van Gogh, Cézanne, Matisse, Hodler',
  'Michael Horowitz',
  'Natur & Symbol',
  'ALBERTINA MODERN The Beginning',
  'My Generation',
];

export default exhibitions;
