const plays = [
  'Die 25. Stunde',
  '69',
  'Ein Abend zu dritt',
  'Der Abenteurer',
  'Der Abenteurer und die Sängerin',
  'Das Abgründige in Herrn Gerstenberg',
  'Der Abiturmann',
  'Der Abstecher (Walser)',
  'Absurda Comica oder Herr Peter Squentz',
  'Der abtrünnige Zar',
  'Adam und Eva',
  'Adelheid von Wulfingen',
  'Der Adept',
  'Ärztinnen',
  'Adrienne Ambrossat',
  'Affäre Dreyfus',
  'Agamemnons Tod',
  'Agnes Bernauer',
  'Agnes Bernauer',
  'Agnes Jordan',
  'Agnes von Meran',
  'Die Ahnfrau',
  'Ajax Lorarius',
  'Alain und Elise',
  'Alcestis, eine artige Tragödie',
  'Alexis',
  'Alfred der Große',
  'Alkestis',
  'Alkestis',
  'Alles um Geld',
  'Alles um Liebe',
  'Alltag',
  'Der Alpenkönig und der Menschenfeind',
  'Als der Krieg zu Ende war',
  'Die alte Jungfer',
  'Das alte Land',
  'Alte Schachteln',
  'Alt-Heidelberg',
  'Altrosa',
  'Amantes amentes…Spiel von der blinden Liebe',
  'Die Amazonen',
  'Am Ende der Nacht',
  'Ein Amerikaner in Berlin',
  'Am Herzogshof',
  'Amphitruo, ein kurtzweilig Spiel',
  'Amphitryon',
  'Anarchie in Bayern',
  'Anarchie in Sillian',
  'Anatol',
  'An der Grenze',
  'Andorra',
  'André Chénier',
  'Angele',
  'Anja und Esther',
  'Anna Walewska',
  'Ein anständiger Mensch',
  'Der Antichrist',
  'Anti-Faust oder Geschichte eines dummen Teufels',
  'Antigone',
  'Apostelspiel',
  'Das Apostelspiel',
  'Die arabische Nacht',
  'Arbeiter, Bauern, Soldaten',
  'Arbeiterpriester',
  'Die Arbeiter von Jersey',
  'Arbeitgeber',
  'Die Argonauten',
  'Ariadne auf Naxos',
  'Ariadne auf Naxos',
  'Armand Carrel',
  'Der arme Heinrich',
  'Der arme Konrad',
  'Der arme Mann Luther',
  'Arme Teufel',
  'Der arme Vetter',
  'Die armseligen Besenbinder',
  'Armut',
  'Armut, Reichtum, Mensch und Tier',
  'Arria und Messalina',
  'Arthur Aronymus und seine Väter',
  'Der Arzt, sein Weib, sein Sohn',
  'Astrid',
  'Asyl in der ersten Welt',
  'Das Attentat auf das Pferd des Brasilianers Joao Candia Bertoza',
  'Auf deutscher Hochschule',
  'Die Aufgeregten von Goethe',
  'Der aufhaltsame Aufstieg des Arturo Ui',
  'Auf jeden Fall verdächtig',
  'Aufstand der Offiziere',
  'Der Aufstieg des Alois Piontek',
  'Aufstieg und Fall der Stadt Mahagonny',
  'Der Auftrag',
  'Die Augenbinde',
  'a unhamlich schtorka abgoung',
  'Die Auseinandersetzung',
  'Die Ausgezeichneten',
  'Der Ausflug ins Sittliche',
  'Der Ausflug mit Damen',
  'Die Ausnahme und die Regel',
  'A Violation Study or El condor pasa',
  'Baal',
  'Babel',
  'Der Babylon Blues oder wie man glücklich wird, ohne sich zu verausgaben',
  'Badenweiler Abgesang',
  'Bäurischer Machiavellus',
  'Die Ballade vom Eulenspiegel, vom Federle und von der dicken Pompanne',
  'Die Ballade vom Wiener Schnitzel',
  'Balsasar, eine lehrhafte Tragödie',
  'Bambiland',
  'Barbara Blomberg',
  'Die Barke von Gawdos',
  'Der Barometermacher auf der Zauberinsel',
  'Bartel Turaser',
  'Der Bataraz',
  'Der Bau',
  'Der Bauer als Millionär oder Das Mädchen aus der Feenwelt',
  'Bauernblut',
  'Bauernoper',
  'Beaumarchais',
  'Der Befehl',
  'Der Befreiungsminister',
  'Begegnung im Herbst',
  'Begegnung mit Herkules',
  'Begegnung mit Ulrike',
  'Begum Somru',
  'Die Behandlung',
  'Die beiden Klingsberg',
  'Die beiden Nachtwandler oder Das Notwendige und das Überflüssige',
  'Das beispielhafte Leben und der Tod des Peter Göring',
  'Bekannte Gesichter, gemischte Gefühle',
  'Belinde',
  'Belisar',
  'Bellman',
  'Die Bergarbeiterinnen',
  'Die Bergknappen',
  'Die Bergschmiede',
  'Das Bergwerk',
  'Das Bergwerk zu Falun',
  'Die Berliner in Wien',
  'Bernhard von Weimar',
  'Ein besserer Herr',
  'Der Besuch aus dem Elysium',
  'Besuch aus dem Paradies',
  'Besuch bei Katt und Fredda',
  'Der Besuch der alten Dame',
  'Besucher',
  'Die Betriebsschließung',
  'Der betrogene Betrug',
  'Der Bettler',
  'Der Bettler von Syrakus',
  'Der Biberpelz',
  'Biedermann und die Brandstifter',
  'Das Bild des Menschen',
  'Billard oder Das Opfer am Grünen Tisch',
  'Biografie: Ein Spiel',
  'Bis zum Horizont',
  'Bismarck',
  'Bismarck oder Warum steht der Soldat da?',
  'Die bitteren Tränen der Petra von Kant',
  'Blanka von Kastilien',
  'Der blaue Boll',
  'Der blaue Sonnenhut',
  'Der Blinde',
  'Das Blumenboot',
  'Blut am Hals der Katze oder Marilyn Monroe contre les vampires',
  'Blut und Liebe',
  'Der Bockerer',
  'Bockgesang',
  'Der böse Geist Lumpazivagabundus oder Das liederliche Kleeblatt',
  'Die bösen Köche',
  'Der Bogen des Odysseus',
  'Bonaparte',
  'Die Boxer',
  'Bräker',
  'Der Brand im Opernhaus',
  'Die Braut von Messina oder Die feindlichen Brüder',
  'Die Brautfahrt oder Kunz von der Rosen',
  'Bremer Freiheit',
  'Der brennende Dornbusch',
  'Bruder Moritz, der Sonderling oder Die Kolonie für die Pelew-Inseln',
  'Ein Bruderzwist in Habsburg',
  'Die Brücke',
  'Brunhild',
  'Brut',
  'Brutus',
  'Des Buches erstes und letztes Blatt',
  'Büchners Tod',
  'Die Büchse der Pandora',
  'buenas noches piaster',
  'Der Bürgergeneral',
  'Bürger Schippel',
  'Bürgermeister Anna',
  'Die Bürger von Calais',
  'Bumerang',
  'Die Burgruine',
  'Buridans Esel',
  'Cäsar',
  'Caféhaus Payer',
  'Camoens',
  'Canossa',
  'Canossa – Eine Katharsis',
  'Cardenio und Celinde oder Unglücklich Verliebte',
  'Carmen Kittel',
  'Carolus Magnus',
  'Carolus Stuardus oder Die ermordete Majestät',
  'Casino Leger',
  'Catharina, Gräfin von Armagnac und ihre beiden Liebhaber',
  'Catilina',
  'Cenodoxus',
  'Change',
  'Charlotte Corday',
  'Die Chinesische Mauer',
  'Chriemhild',
  'Christa die Tante',
  'Christinas Heimreise',
  'Christoph Marlow',
  'Clara S.',
  'Claudius',
  'Claus Peymann kauft sich eine Hose und geht mit mir essen',
  'Clavigo',
  'Clowns',
  'Die Clowns von Avignon',
  'Comoedia vom Studenten-Leben',
  'Conflagratio Sodomae, eine erschröckliche Tragödia',
  'Conradine',
  'Cordatus',
  'Corinne und der Seebär',
  'Cornelius Relegatus',
  'Die Corsen',
  'Creeps',
  'Cyankali',
  'Damon oder die wahre Freundschaft',
  'Dankmar',
  'Dantons Tod',
  'Darja',
  'Dat Gaap-Pulwer',
  'Datterich',
  'David und Goliath',
  'Demetrios',
  'Demetrius',
  'Die Demonstration',
  'Die deutsche Hausfrau',
  'Der deutsche Mann und die vornehmen Leute',
  'Die deutschen Kleinstädter',
  'Der Diamant',
  'Der Diamant des Geisterkönigs',
  'Der natürliche Vater',
  'Dichtung und Wahrheit oder Der Pestalozzi-Preis',
  'Dies irae',
  'Dissonanzen',
  'Doctor Wespe',
  'Doktor Semmelweis',
  'Dolomitenstadt Lienz',
  'Donadieu',
  'Donauballade',
  'Die Donaubrücke',
  'Donau so blau',
  'Don Carlos',
  'Don Juan kommt aus dem Krieg',
  'Don Juan oder Die Liebe zur Geometrie',
  'Don Juan Tenorio',
  'Don Juan und Faust',
  'Donnerstag',
  'Doppelkopf',
  'Doppelselbstmord',
  'Das Dorf bei Odessa',
  'Dorf und Stadt',
  'Die Dorfstraße',
  'Dr. med. Hiob Prätorius, Facharzt für Chirurgie und Frauenleiden',
  'Dr. med. Hiob Prätorius',
  'Draußen vor der Tür',
  'Drei',
  'Drei',
  'Drei Akte',
  'Drei ehrenwerte Herren',
  'Die Dreigroschenoper',
  'Die drei Reiherfedern',
  'Die drei Zwillinge',
  'Der Drosselgesang vor dem Tode Dornröschens berauscht die Zuckerbäcker, die in der Sonne zerfließen',
  'Drunter, Drüber',
  'Du bist der Richtige',
  'Duell an der Havel',
  'Dunant',
  'Das Ebenbild eines gehorsamen Glaubens',
  'Die echten Sedemunds',
  'Edelwild',
  'Die edle Lüge',
  'Egmont',
  'Die Ehe',
  'Die Ehe des Herrn Mississippi',
  'Die Ehre',
  'Eiche und Angora',
  'EiferSucht',
  'Eifersucht ist eine Leidenschaft',
  'Einsame Menschen',
  'Die einsame Tat',
  'Der einsame Weg',
  'Der Einsiedler von Sanssouci',
  'Einzug ins Schloß',
  'Eisenbahnheirathen oder Wien, Neustadt, Brünn',
  'Eisenwichser',
  'Der Eisgang',
  'Eiszeit',
  'Elektra',
  'Elfriede',
  'Elga',
  'Elio oder Eine fröhliche Gesellschaft',
  'Elisabeth II.',
  'Emilia Galotti',
  'Das Ende des friedlichens Lebens der Else Reber',
  'Ende und Anfang',
  'Die endlose Straße',
  'Ein Engel kommt nach Babylon',
  'Der Engel mit dem Saitenspiel',
  'Der englische Sender',
  'Der entfesselte Wotan',
  'Die Entkleidung des Antonio Carossa',
  'Entscheiden Sie sich',
  'Die Entscheidung der Lene Mattke',
  'Ephraims Breite',
  'Das Epigramm',
  'Der Erbförster',
  'Erdgeist',
  'Erika',
  'Die Ermittlung',
  'Die Ermordung des Aias oder Ein Diskurs über das Holzhacken',
  'Die Eroberung der Prinzessin Turandot',
  'Die Eroberung des Südpols',
  'Eröffnung des indischen Zeitalters',
  'Der erschlagene Schatten',
  'Der Erste',
  'Erster Klasse',
  'Die ersten Schritte',
  'Des Esels Schatten oder Der Galatag in Krähwinkel',
  'Es lebe das Leben',
  'Es steht geschrieben',
  'Esther',
  'Etappe',
  'Etagenvögel',
  'Europa',
  "Evchen Humbrecht oder Ihr Mütter, merkt's Euch!",
  'Der ewige Traum',
  'Die Exzesse',
  'Ezelin von Romano',
  'Die Fabier',
  'Fabrik im Walde',
  'Der Fährmann von Dürnstein',
  'Der Färber und sein Zwillingsbruder',
  'Die Fahnenweihe',
  'Der fahrend Schüler im Paradeis',
  'Ein Fahrplan stimmt nicht mehr',
  'Die falschen Spieler',
  'Die Familie Schroffenstein',
  'Die Familie Makabah',
  'Die Familie von Nevada',
  'Fanal',
  'Fast ein Prolet',
  'Ein Fastnachtsspiel vom Pater Brey',
  'Faust I',
  'Faust II',
  'Faust III',
  'Faustens Ende',
  'Der Fechter von Ravenna',
  'Fegefeuer in Ingolstadt',
  'Feierabend I und II',
  'Der Feigling',
  'Ein Fest für Boris',
  'Die Feststellung',
  'Feuer aus den Kesseln',
  'Feuerfuß (Emphase für Bühne)',
  'Figaro lässt sich scheiden',
  'Filia hospitalis',
  'Filipa unterwegs',
  'Film und Frau',
  'Der Findling (Barlach)',
  'Fiorenza',
  'Der Fisch mit dem goldenen Dolch',
  'Die Fische',
  'Ein Flaschenreich für die Erde',
  'Florian Geyer',
  'Floridsdorf',
  'Das Floß der Medusa',
  'Die Flotte',
  'Der Flüchtling (Hochwälder)',
  'Der Fluch des Galilei',
  'Flucht nach Hinterwiesenthal',
  'Die Flucht nach Venedig',
  'Fortunatas Biß',
  'Das Fossil',
  'Frank der Fünfte',
  'Frankenstein am Main',
  'Frankfurter Kreuz',
  'Franziska',
  'Franziska Lesser',
  'Die Frau auf dem Teller',
  'Der Frauenarzt',
  'Frauenmut',
  'Das Frauen-Opfer',
  'Die Frauen von Utopia',
  'Die Frau im Fenster',
  'Frau Flinz',
  'Freibrief',
  'Die Freier',
  'Der Freigeist',
  'Der Freigeist',
  'Freiheit',
  'Die Freiheit',
  'Freiheit für Clemens',
  'Freiheit in Krähwinkel',
  'Der Freiheitsbaum',
  'Friedas Reise',
  'Das Friedensfest',
  'Friede wünschendes Teutschland',
  'Friedrich II.',
  'Friedrich und Anna',
  'Der fröhliche Weinberg',
  'Frühere Verhältnisse',
  'Frühlings Erwachen',
  'Frühlingsopfer',
  'Frühstückspause',
  'Die Fuchsfalle',
  'Die fünfte Jahreszeit',
  'Fünfzehn Schnüre Geld',
  'Fünfzehn, Sechzehn, Siebzehn',
  'Für alle ein Jojo',
  'Fuhrmann Henschel',
  'Furcht und Elend des Dritten Reiches',
  'Gabriel Schillings Flucht',
  'Gabriele Dambrone',
  'Der Gärtner von Toulouse',
  'Gandha',
  'Gas I',
  'Gas II',
  'Der Gast',
  'Der Gastfreund',
  'Das Gastmahl des Plato',
  'Gats',
  'Gawan',
  'Geburt der Jugend',
  'Die gefesselte Phantasie',
  'Gegen die Wand',
  'Geist und Fleisch',
  'Geist von Cranitz',
  'Geisterbahn',
  'Geld',
  'Die geliebte Dornrose',
  'Das Gelübde',
  'General Landt',
  'Genoveva',
  'Der gerettete Alkibiades',
  'Das gerettete Venedig',
  'Gericht über Zarathustra',
  'Gerichtet in der Stadt',
  'Das Gericht Salomonis',
  'Germanen und Römer',
  'Germania, ein Trauerspiel',
  'Germania Tod in Berlin',
  'Germinal',
  'Der Gesang im Feuerofen',
  'Die Geschichten vom Dreizehnten',
  'Die Geschwister',
  'Die Gesellschaft des Abbé Chateauneuf',
  'Gesellschaft im Herbst',
  'Das Gesetz in Dir',
  'Das Gesicht',
  'Die Gesichte der Simone Machard',
  'Ein Geschlecht',
  'August von Kotzebue',
  'Gespenster',
  'Ein Gespräch im Hause Stein über den abwesenden Herrn von Goethe',
  'Geschichten aus dem Wiener Wald',
  'Gestern',
  'Der gestiefelte Kater',
  'Der gestohlene Gott',
  'Der gestürzte Markgraf von Ancre',
  'Die Gewaltlosen',
  'Die Gewehre der Frau Carrar',
  'Das Gewitter',
  'Der Gigant',
  'Gilgamesh',
  'Gilles',
  'Gisela Elsner - Blickwinkel 2017',
  'Die gläserne Frau',
  'Glastüren',
  'Der gläserne Pantoffel',
  'Glaube Liebe Hoffnung',
  'Glaube und Heimat',
  'Das Gleichgewicht',
  'Das Glück im Winkel',
  'Die Glückskuh',
  'Goldberg-Variationen',
  'Die goldene Harfe',
  'Die goldenen Straßen',
  'Golden fließt der Stahl',
  'Der goldene Vogel',
  'Das goldene Vlies',
  'Goncourt oder Die Abschaffung des Todes',
  'Göttinger Kantate',
  'Götz von Berlichingen',
  'Gottes General',
  'Gotthelm oder Mythos Claus',
  'Die Gräfin von Rathenow',
  'Graf Grün oder Die Notwendigkeit der Räuber',
  'Graf Öderland',
  'Der Graf von Burgund',
  'Der Graf von Charolais',
  'Der Graf von Gleichen',
  'Der Graf von Ratzeburg',
  'Graf Waldemar',
  'Gregor und Heinrich',
  'Grenzwacht',
  'Grischa',
  'Griseldis',
  'Griseldis',
  'Der Große Kurfürst',
  'Der große Wolf',
  'Der Großinquisitor',
  'Der Groß-Kophta',
  'Groß und klein',
  'Große Schmährede an der Stadtmauer',
  'Die Großstadtluft',
  'Die große Sünde',
  'Die große Wut des Philipp Hotz',
  'Großvater und Halbbruder',
  'Der grüne Kakadu',
  'Der Gruftwächter',
  'Gudrun',
  'Gudrun',
  'Guerillas',
  'Guevara oder Der Sonnenstaat',
  'Gust',
  'Gustav Wasa',
  'Der gute Mensch von Sezuan',
  'Die guten Feinde',
  'Die gutgeschnittene Ecke',
  'Der G’wissenswurm',
  'Gyges und sein Ring',
  'Haben',
  'Häuptling Abendwind oder Das greuliche Festmahl',
  'Die Hagestolze',
  'Der Hahn',
  'Der Hahnenkampf',
  'Der Hakim weiß es',
  'Halbdeutsch',
  'Ein halber Held',
  'Hamlet in Wittenberg',
  'Hamletmaschine',
  'Die Handwerker kommen',
  'Hanna Jagert',
  'Hanneles Himmelfahrt',
  'Hannibal',
  'Hans Eschelbach - Worte und Werte',
  'Hans Faust',
  'Hans im Schnakenloch',
  'Hans Kirch',
  'Hanserl',
  'Hartnäckig',
  'Die Hasenpfote',
  'Die Haubenlerche',
  'Der Hauptmann und sein Held',
  'Der Hauptmann von Köpenick',
  'Das Haus am Meer',
  'Das Haus der Temperamente',
  'Das Haus in Montevideo',
  'Haushalt oder Die Sandhasen',
  'Haut oder Hemd',
  'Hecuba, eine klägliche Tragödie',
  'Der heilige Crispin',
  'Die heilige Ehe',
  'Das heilige Experiment',
  'Die heilige Johanna der Schlachthöfe',
  'Heimarbeit',
  'Heimat',
  'Heimat',
  'Die Heimkehr des Matthias Bruck',
  'Heinrich und Heinrichs Geschlecht',
  'Heinrich Schlaghands Höllenfahrt',
  'Heinrich VIII. oder Der Ketzerkönig',
  'Die Heirat wider Willen',
  'Heldenplatz',
  'Hellseherei',
  'Helm',
  'Heloisa und Abaelard',
  'Henkersnachtmahl',
  'Herakles',
  'Herakles 5',
  'Herbstball',
  'Herkules und der Stall des Augias',
  'Die Herberge',
  'Die Hermannsschlacht',
  'Die Hermannsschlacht',
  'Hermes in der Stadt',
  'Herodes und Mariamne',
  'Heroische Leidenschaften',
  'Der Herr Karl',
  'Herr Puntila und sein Knecht Matti',
  'Herrmann',
  'Herzmündung',
  'Herzog Theodor von Gothland',
  'Heute ist ein guter Tag',
  'Die Hexe von Passau',
  'Hexenritt',
  'Hexenspiel',
  'Hidalla oder Karl Hetmann, der Zwergriese',
  'Hilfe, ich werde geheiratet!',
  'Hilferufe',
  'Der Himbeerpflücker',
  'Himmel sehen',
  'Himmel und Erde',
  'Himmel und Hölle',
  'Himmelfahrt zur Erde',
  'Hin und Her',
  'Die Hinrichtung',
  'Hinkemann',
  'Hiob',
  'Hiob',
  'Hochwasser',
  'Die Hochzeit der Sobeide',
  'Die Hochzeit des Adrian Brouwer',
  'Hochzeiter und Hochzeiterin',
  'Die Hochzeitsreise nach Heidelberg',
  'Höhenluft',
  'Das höhere Leben',
  'Hölderlin',
  'Hölle Weg Erde',
  'Das Hofgesind der Venus',
  'Der Hofmeister oder Die Vorteile der Privaterziehung',
  'Hokuspokus',
  'Die Holländerbraut',
  'Hoppla, wir leben!',
  'Der Horatier',
  'Gerhard Winterlich',
  'Horribilicribrifax oder Wählende Liebhaber',
  'Die Hose',
  'Hotel du Commerce',
  'Hotel zur schönen Aussicht',
  'Hugo Grotius',
  'Der Hulla',
  'Der Hund des Generals',
  'Hundlich',
  'Der Hundsprozess',
  'Die Hungerkünstler',
  'Die Hure Gerhild',
  'Die Hussiten vor Naumburg im Jahr 1432',
  'Der Hut von Joseph Beuys',
  'Die Hypochonder',
  'Ich betone, daß ich nicht das geringste an der Regierung auszusetzen habe',
  'Ich bin einem Mädchen begegnet',
  'Ich und Du',
  'Ich wollte meine Tochter läge tot zu meinen Füssen und hätte die Juwelen in den Ohren',
  'Der Ignorant und der Wahnsinnige',
  'Die Illegalen',
  'Im Himmlischen Garten',
  'Imelda Lambertazzi',
  'Im Maien',
  'Die im Schatten leben',
  'In der Löwengrube',
  'In der Sache J. Robert Oppenheimer',
  'Die Indianer in England',
  'In einer Nacht',
  'In Ewigkeit Amen',
  'In Sachen Adam und Eva',
  'Indipohdi',
  'Ingeborg',
  'Iphigenie auf Tauris',
  'Iphigenie in Aulis',
  'Iphigenie in Delphi',
  'Iphigenie in Delphi',
  'Italienische Nacht',
  'Im Walde von Toulouse',
  'Jacke wie Hose',
  'Jacobowsky und der Oberst',
  'Die Jäger',
  'Die Jagdgesellschaft',
  'Jagdszenen aus Niederbayern',
  'Jahresringe',
  'Jahrmarktsfest zu Plundersweilern',
  'Jailhouse Blues',
  'Jan der Wunderbare',
  'Jean Henry Dunant oder Die Einführung der Zivilisation',
  "Jeanne d'Arc",
  'Jedermann',
  'Ein Jedermann',
  'Jehr',
  'Jenseits der Angst',
  'Jenseits vom Paradies',
  'Jenseits von Gut und Böse oder Die letzten Tage der Reichskanzlei',
  'Jeremia, eine geistliche Tragödie',
  'Jeremias',
  'Jerusalem Jerusalem',
  'Joel Brand',
  'Johann Christian Günther',
  'Johann Georg Elser',
  'Johann Orth',
  'Johanna von Döbeln',
  'Johanna von Montfaucon',
  'Johannisfeuer',
  'Johannistrieb',
  'Josephine',
  'Josephus',
  'Die Journalisten',
  'Juana',
  'Juarez und Maximilian',
  'Jubiläum',
  'Der Judas von Tirol',
  'Die Jüdin von Toledo',
  'Die jüdische Witwe',
  'Die Juden',
  'Die Judenbank',
  'Jud Süß',
  'Der Jude von Konstanz',
  'Judith',
  'Judith',
  'Judith und Holofernes',
  'Jugend',
  'Julia',
  'Julius von Tarent',
  'Der junge Baron Neuhaus',
  'Der junge Gelehrte',
  'Der junge Luther',
  'Die jungen Ritter vor Sempach',
  'Der junge Parzival',
  'Die junge Welt',
  'Die Jungfern vom Bischofsberg',
  'Die Jungfrau von Orléans',
  'Juristen',
  'Einen Jux will er sich machen',
  'Kabale und Liebe',
  'Das Käthchen von Heilbronn',
  'Kain',
  'Kaiser Franz Joseph I. von Österreich',
  'Kaiser Joseph und die Bahnwärterstochter',
  'Kaiser Karls Geisel',
  'Kaiser Maxens Brautfahrt',
  'Der Kaiser und die Hexe',
  'Des Kaisers Soldaten',
  'Kakadu-Kakada',
  'Das kalte Licht',
  'Kampf ums Reich',
  'Der Kammersänger',
  'Die Kampagne',
  'Der Kampf ums Rosenrote',
  'Die Kannibalen',
  'Kap der Unruhe',
  'Kaprun',
  'Karagöz in Alamania',
  'Karandasch',
  'Die Karlsschüler',
  'Kasimir und Karoline',
  'Kaspar',
  'Kassandra',
  'Die Kassette',
  'Kater Lampe',
  'Katharina Knie',
  'Katharina von Georgien',
  'Katte',
  'Die Katze',
  'Katzelmacher',
  'Katzengold',
  'Katzgraben',
  'Der Kaufmann von Berlin',
  'Der kaukasische Kreidekreis',
  'Kaution',
  'Kein Platz für Idioten',
  'Der Keller',
  'Kellers Abend',
  'Kennen Sie die Milchstraße?',
  'Das Kerbelgericht',
  'Der keusche Joseph',
  'Kiez',
  'Kilian oder Die gelbe Rose',
  'Die Kinder Godunófs',
  'Die Kinder (Bahr)',
  'Die Kindermörderin',
  'Das Kind der Liebe',
  'Kinder und Narren',
  'Ein Kinderspiel',
  'Kindsmord',
  'Kipper Paul Bauch',
  'Klamms Krieg',
  'Klara und der Gänserich',
  'Klarissas halbes Herz',
  'Die Kleinbürgerhochzeit',
  'Kleine Fallen für die Füchse',
  'Kleine Gefängnisse Große Fluchten',
  'Kleine Sklavin',
  'Das kleine Welttheater oder Die Glücklichen',
  'Das kleine Weltwirtshaus',
  'Klettwitzer Berichte',
  'Klopfzeichen 7',
  'Klopfzeichen. Leuchtfeuer. Rauchsignale.',
  'Knut der Herr',
  'König David',
  'König David',
  'König Hahnrei',
  'Eine Königin',
  'König Ludwig I. und Lola Montez',
  'König Nicolo oder So ist das Leben',
  'König Ottokars Glück und Ende',
  'Das Königreich',
  'Kohlhaas',
  'Kolberg',
  'Kollege Crampton',
  'Kollegen',
  'Kolonne Immergrün',
  'Kolportage',
  'Komödie der Verführung',
  'Der konfuse Zuschauer',
  'Kong - Monolog für einen fremden Helden',
  'Konrad oder das Kind aus der Konservenbüchse',
  'Konradin von Hohenstaufen',
  'Der Kontrabaß',
  'Das Konzert',
  'Die Koralle',
  'Koralle Meier',
  'Korczak und die Kinder',
  'Die Korrektur',
  'Kräfte',
  'Der Krampus',
  'Kranichtanz',
  'Krankheit der Jugend',
  'Das Kreuz an der Ostsee',
  'Die Kreuzelschreiber',
  'Die Kreuzigung Christi',
  'Kreuzweg',
  'Krieg den Philistern',
  'Krisis',
  'Die Krönung Richard III.',
  'Die Kummideesitzung',
  'Kuriöser Körbelmacher',
  'Die Kurve',
  'Kybernetische Hochzeit',
  'Die Lachtaube',
  'Lady Liljas Hauer',
  'Die Lästigen',
  'Das Lamm der Armen',
  'Der Lampenschirm',
  'Lancelot',
  'Landschaft mit Figuren',
  'Landshuter Erzählungen',
  'Die lange Jule',
  'Die lange Nacht der Detektive',
  'Der lange Weg zu Lenin',
  'Lanval',
  'La Peyrouse',
  'Lappschieß',
  'Laternenfest',
  'Die Laune des Verliebten',
  'Lazaretti oder Der Säbeltiger',
  'Leben des Galilei',
  'Das Leben des Horace A. W. Tabor',
  'Das Leben ein Traum',
  'Leben und Tod der heiligen Genoveva',
  'Leben und Tod des kleinen Rothkäppchens',
  'Leben und Tod der Marilyn Monroe',
  'Le Corbusier baut Berliner Flughafen',
  'Die Lederköpfe',
  'Legende eines Lebens',
  'Das leidende Weib',
  'Ein Leidensweg',
  'Leinen aus Irland',
  'Leistungskontrolle',
  'Leitfaden',
  'Die letzte Station',
  'Die letzten Masken',
  'Die letzten Tage der Menschheit',
  'Das Liebeskonzil',
  'Der Liebestrank',
  'Das Lied meines Weges',
  'Leo Armenius',
  'Leonce und Lena',
  'Les adieux oder Die Schlacht bei Stötteritz',
  'Letzte Nacht im September',
  'Letzter Sommer in Heidkau',
  'Leuchtfeuer',
  'Leyla, Leyla',
  'Libussa',
  'Liebe',
  'Liebe in Florenz',
  'Liebelei',
  'Lieber Fritz',
  'Liebesgeschichten und Heurathssachen',
  'Li-Lifan oder Das Glück der Konkubinen',
  'Liliom',
  'LKW',
  'Das Lob des Landes',
  'Lobgesänge des Claudian',
  'Lofter oder Das zweite Gesicht',
  'Lohnhof',
  'Der Lohndrücker',
  'Die Lokalbahn',
  'Lombard gibt den Letzten',
  'Lope de Vega',
  'Ein Lorbaß',
  'Lord Byron kommt aus der Mode',
  'Das Los des Ossian Balvesen',
  'Lottchens Geburtstag',
  'Louis Ferdinand, Prinz von Preußen',
  'Lovely Rita',
  'Lucie de Beaune',
  'Lucifer',
  'Der Lügner und die Nonne',
  'Lützower',
  'Lulu live',
  'Lumpengesindel',
  'Der Luzerner Löwe',
  'Lysiane',
  'M',
  'Die Macht der Gewohnheit',
  'Madame Legros',
  'Das Mädchen aus der Fremde',
  'Das Mädchen aus der Feenwelt oder Der Bauer als Millionär',
  'Das Mädchen mit Millionen oder Die Nähterin',
  'Das Mädel aus der Vorstadt oder Ehrlich währt am längsten',
  'Die Männerfrage',
  'Männersache',
  'Das Märchen vom Wolf',
  'März, ein Künstlerleben',
  'Magdalena',
  'Magic Afternoon',
  'Die magische Laterne',
  'Magister Tinius',
  'Magnetküsse',
  'Magnus Garbe',
  'Makart',
  'Die Makkabäer',
  'Die Marneschlacht',
  'Mammons Sold',
  'Mann ist Mann',
  'Der Mann mit dem Vogel',
  'Manon Lescaut',
  'Manuel und die Giraffen',
  'Margarete in Aix',
  'Maria da Molina',
  'Maria Magdalena',
  'Maria Stuart',
  'Marianne',
  'Marie von Brinvilliers, Liebende, Giftmischerin und Marquise',
  'Die Marquise von Arcis',
  'Der Marquis von Keith',
  'Marski',
  'Martinisommer',
  'Martin Lehnhardt. Ein Kampf um Gott',
  'Martin Luther',
  'Martin Luther oder Die Weihe der Kraft',
  'Martin Luther & Thomas Münzer oder Die Einführung der Buchhaltung',
  'Mary Stuart',
  'März, ein Künstlerleben',
  'Masada',
  'Maschinenstürmer',
  'Masse Mensch',
  'Die Massen von Hsunhi',
  'Die Massenmörderin und ihre Freunde',
  'Die Maßnahme',
  'Die Matrosen von Cattaro',
  'Die Mausefalle',
  'Mauser',
  'Mauserung',
  'McKinsey kommt',
  'Die Medaille',
  'Medea',
  'Medea',
  'Medea in Korinth',
  'Des Meeres und der Liebe Wellen',
  'Meier Helmbrecht',
  'Meierbeths Glück und Ende',
  'Der Meineidbauer',
  'Mein Kampf',
  'Der Meister',
  'Der Meister von Palmyra',
  'Melusine',
  'Memmingen',
  'Memory Hotel',
  'Mensch Meier',
  'Die Menschen',
  'Die Menschenfresser',
  'Menschenhass und Reue',
  'Merlin',
  'Merlins Geburt',
  'Meroe',
  'Die Merowinger',
  'Mesalliance, aber wir ficken uns prächtig',
  'Metanoeite (Theaterstück)',
  'Der Meteor',
  'Michael Kramer',
  'Michel Angelo',
  'Michel Michael',
  'Michis Blut',
  'Mieze und Maria',
  'Ein mildes Urteil',
  'Der Millionenschmidt',
  'Minetti',
  'Der Ministerpräsident',
  'Minna von Barnhelm',
  'Das Mirakel',
  'Der Misogyn',
  'Miss Rollschuh',
  'Miss Sara Sampson',
  'Mississippi',
  'Der Mitmacher',
  'Der Mitmensch',
  'Die Mitschuldigen',
  'Die Mittagsgöttin',
  'Mohrenwäsche',
  'Die Mohrin',
  'Mohr von Wien',
  'Moral',
  'Mord',
  'Mörder, Hoffnung der Frauen',
  'Morgen kommt der Schornsteinfeger',
  'Die Morgenröte',
  'Morituri',
  'Moritz Tassow',
  'Mudder Mews',
  'Der Müll, die Stadt und der Tod',
  'Müller, Kohlenbrenner und Sesseltrager oder die Träume von Schale und Kern',
  'Der Müller von Sanssouci',
  'Münchhausen',
  'Münchner Freiheit',
  'Münchner Kindl',
  'Das Mündel will Vormund sein',
  'Die Mütter',
  'Murx den Europäer',
  'Musik',
  'Das Musikantendorf',
  'Der mutige Seefahrer',
  'Die Mutter (Bahr)',
  'Die Mutter',
  'Mutter Courage und ihre Kinder',
  'Mutter Erde',
  'Mutter Landstraße',
  'Mutter Sorge',
  'Mutters Courage',
  'Mythenspiel',
  'Das Nachfolge-Christi-Spiel',
  'Der Nachfolger',
  'Die Nacht der Hirten',
  'Die Nacht, in der der Chef geschlachtet wurde',
  'Nacht mit Gästen',
  'Nachtblind',
  'Eine Nacht in Florenz',
  'Nachtlogis',
  'Nachsaison',
  'Nachtstück',
  'Nachtwache',
  'Nachtzug',
  'Nacktes Gras',
  'Nante',
  'Napoleon Bonaparte',
  'Napoleon in New Orleans',
  'Napoleon oder Die hundert Tage',
  'Der Narr und seine Frau heute abend in Pancomedia',
  'Das Narrenfest',
  'Nathan der Weise',
  'Nathans Tod',
  'Die natürliche Tochter',
  'Der natürliche Vater',
  'Nausikaa',
  'Der Nebbich',
  'Nebeneinander',
  'Neithardt von Gneisenau',
  'Nepal',
  'Das Nest',
  'Die Neuberin',
  'Die neue Arria',
  'Das neue Jahrhundert',
  'Der neue Mendoza oder Die Geschichte des cumbanischen Prinzen Tandi',
  'Die neuen Leiden des jungen W.',
  'Die neuen Menschen',
  'Neuer Lübecker Totentanz',
  'Die Nibelungen',
  'Der Nibelunge Not',
  'Nichts Neues aus Hollywood',
  'Nickel und die sechsunddreißig Gerechten',
  'Night-step',
  'Nina',
  'Ninon de Lenclos',
  'Ninon de Lenclos',
  'Noch zehn Minuten bis Buffalo',
  'Noli me tangere',
  'Die Nonnen von Kemnade',
  'Nordost',
  'Norway.today',
  'November in Österreich',
  'Nun singen sie wieder',
  'Nur keck',
  'Oaha',
  'Oberösterreich',
  'Oberst Chabert',
  'Odysseus',
  'Odysseus muß wieder reisen',
  'Der öffentliche Ankläger',
  'Offiziere',
  'Oktobertag',
  'Olaf und Albert',
  'Ollapotrida',
  'Olympia',
  'Omelette surprise',
  'Omphale',
  'Onkel, Onkel',
  'Das Opfer der Agnete',
  'Das Opfer Helena',
  'Der Opfergang des Johann Philipp Palm',
  'Das Opfer in Arkadia',
  'Der Opfer-Tod',
  'Die Opferung',
  'Orest und Pylades',
  'Orfeus',
  'Orpheus und Eurydike',
  'Oscar Wilde',
  'Ökodation 2028',
  'Österreichische Komödie',
  'Ostpolzug',
  'Ostrom',
  'Otto',
  'Ozean',
  'Paare, Passanten',
  'Pachter Feldkümmel von Tippelskirchen',
  'Die Päpstin Johanna',
  'Pagenstreiche',
  'Palme oder Der Gekränkte',
  'Pankratz erwacht',
  'Panoptikum',
  'Pantalon und seine Söhne',
  'Der Papagoy',
  'Die Papiermühle',
  'Papinianus',
  'Paracelsus',
  'Pardon wird nicht gegeben',
  'Der Park',
  'Das Partikular',
  'Partner',
  'Party for Six',
  'Die Passion',
  'Pastor Ephraim Magnus',
  'Pastor Hall',
  'Pastorale oder Die Zeit für Kakao',
  'Der Patriot',
  'Patrioten',
  'Paula Ludwig-Freundschaften und Wege',
  'Paulus unter den Juden',
  'Peep Show',
  'Pension Schöller',
  'Penthesilea',
  'Perchtenspiel',
  'Ein permanenter Dämmerschoppen',
  'Persephone',
  'Peter Brauer',
  'Peter und Alexej',
  'Der Pfarrer von Kirchfeld',
  'Die Pfarrhauskomödie',
  'Pfingstläuten',
  'Pflicht zur Sünde',
  'Phaea',
  'Der Phantast',
  'Philemon Martyr',
  'Philemon und Baukis',
  'Philoktet',
  'Die Physiker',
  'Philotas',
  'Pinkville',
  'Pioniere in Ingolstadt',
  'Planspiel',
  'Play Strindberg',
  'Die Plebejer proben den Aufstand',
  'Politica dramatica, das ist Die Edle Regimentskunst',
  'Politik',
  'Polly oder Die Bataille am Bluewater Creek',
  'Polterabend',
  'Pompinien',
  'Porträt eines Planeten',
  'Die portugalesische Schlacht',
  'Der Präsident',
  'Der Präsident',
  'Pre-Paradise Sorry Now',
  'Predigt in Litauen',
  'Preußengeist',
  'Prima Ballerina',
  'Prinz Dschem',
  'Prinz Friedrich von Homburg',
  'Prinz Zerbino oder Die Reise nach dem guten Geschmack',
  'Das Prinzip',
  'Probekandidat',
  'Das Produkt',
  'Professor Bernhardi',
  'Professor Mamlock',
  'Der Protagonist',
  'Prozeß in Nürnberg',
  'Die Prüfung des Meister Tilman',
  'Publikumsbeschimpfung',
  'Push Up 1-3',
  'Quartett',
  'Die Quitzows',
  'Querelle',
  'Quodlibet',
  'Die Räuber',
  'Die Räumung',
  'Die Rantzau und die Pogwisch',
  'Die Raschhoffs',
  'Die Ratten',
  'Der Rattenfänger',
  'Der Raub der Sabinerinnen',
  'Rauhnacht',
  'Ravensbrücker Ballade',
  'Der Regenwettermann',
  'Der Rehbock oder Die schuldlosen Schuldbewußten',
  'Das Reich Gottes in Böhmen',
  'Reigen',
  'Die Reise des Engin Özkartal von Nevsehir nach Herne und zurück',
  'Reise nach Ursprung',
  'Rektor Kleist',
  'Reparationen',
  'Requiem für einen Spion',
  'Der Retter',
  'Revolution des Herzens',
  'Rheinische Rebellen',
  'Die Richterin',
  'Der Ring des Gauklers',
  'Klaus Fehling',
  'Der Ritt über den Bodensee',
  'Ritter, Dene, Voss',
  'Ritter Blaubart',
  'Ritter Blaubart',
  'Ritter Lanval',
  'Riviera',
  'Robert Emmet',
  'Robert Guiskard',
  'Robinson soll nicht sterben',
  'Roll Over Beethoven',
  'Rom oder Die zweite Erschaffung der Welt',
  'Romeo und Julia in Berlin',
  'Romulus der Grosse',
  'Rosamunde Floris',
  'Rose Bernd',
  'Rosengarten',
  'Rosenmontag',
  'Rösikes Geist',
  'Rosse',
  'Der rote Bräutigam',
  'Der rote Hahn',
  'Die rote Mühle',
  'Die Rotte Kain',
  'Rotter',
  'Rozznjogd',
  'Rübezahl',
  'Die Rückkehr',
  'Die Rückkehr des Alkestis',
  'Rückkehr in die Wüste',
  'Der Rubin',
  'Ruhmlose Helden',
  'Ruhrkampfrevue',
  'Rumpelstilz',
  'Der Sacco',
  'Säuberung in Ithaka',
  'Salongespräche oder Die Chronik der geistigen Wunder schimmert fahl und zweideutig',
  'Das Salzburger große Welttheater',
  'Sampiero',
  'Sancta Susanna',
  'Santa Cruz',
  'Sappho',
  'Das Sauspiel',
  'Saul, eine klägliche Tragödie',
  'Scapa Flow',
  'Schach dem König',
  'Der Schatz',
  'Die Schauspieler',
  'Die Schauspielerin',
  'Der Schein trügt',
  'Scheiß Napoleon',
  'Der Schelm vom Kahlenberg',
  'Der Schelm von Bergen',
  'Der Schelm von Limburg',
  'Scherenschnitt',
  'Scherz, Satire, Ironie und tiefere Bedeutung',
  'Schichtwechsel',
  'Schicksalskomödie',
  'Schneewittchen und die (fast) 7 Zwerge',
  'Der schiefe Turm von Pisa',
  'Das Schiff auf der Donau',
  'Schinderhannes',
  'Der Schinderhannes',
  'Die Schlacht bei Lobositz',
  'Schlag dreizehn',
  'Der Schleier der Beatrice',
  'Die schlimme Botschaft',
  'Die schlimmen Buben in der Schule',
  'Schloß Wetterstein',
  'Ein Schluck Erde',
  'Schluck und Jau',
  'Schlußchor',
  'Die Schmetterlingsschlacht',
  'Schneider Wibbel',
  'Der Schmied von Kochel',
  'Der Schnellmaler oder Kunst und Mammon',
  'Das Schreibepult oder Die Gefahren der Jugend',
  'Ein Schritt vom Wege',
  'Der Schulfreund',
  'Der Schuss in die Öffentlichkeit',
  'Der Schuster und der Hahn',
  'Der Schütze Tell',
  'Der Schutzgeist',
  'Der Schützling',
  'Die Schwärmer',
  'Der Schwan',
  'Der schwangere Bauer',
  'Die schwarze Maske',
  'Der schwarze Schwan',
  'Schweig Bub!',
  'Schweyk im Zweiten Weltkrieg',
  'Der Schwierige',
  'Der Schwur',
  'Die sechste Frau',
  'Seelenwanderung',
  'Seeschlacht',
  'Sein Leben',
  'Seine Kinder',
  'Selber schuld',
  'Selbstbezichtigung',
  'Der Selbstmörder',
  'Die seltsame Reise des Alois Fingerlein',
  'Semiramis',
  'Seneca',
  'Senftenberger Erzählungen oder Die Enteignung',
  'Ein sehr kurzes Stück für Bankdirektoren',
  'Servet in Genf',
  'Shackleton: Banjo oder Bibel?',
  'Shakespeare dringend gesucht',
  'Sherlock Holmes',
  'Sibirien',
  'Sie werden sterben, Sire',
  'Sieben gegen Theben',
  'Sieben Wünsche',
  'Siebenstein',
  'Die Siebzehnjährigen',
  'Sigmunds Freude',
  'Die silberne Hochzeit',
  'Der Silbersee',
  'Silvester oder Das Massaker im Hotel Sacher',
  'Silvia im Stern',
  'Simson, eine geistliche Tragödie',
  'Simson',
  'Simsone Grisaldo',
  'Der singende Fisch',
  'Der Snob',
  'Die Söhne des Tals',
  'Der Sohn',
  'Der Sohn der Wildnis',
  'Der Soldat Tanaka',
  'Der Soldat und das Feuerzeug',
  'Die Soldaten',
  'Der Sommer am Neusiedler See',
  'Der Sommerbürger',
  'Die Sonnenjungfrau',
  'Die Sorgen und die Macht',
  'Die Sorina',
  'So war Herr Brummel',
  'Sodoms Ende',
  'Soldaten, Nekrolog auf Genf',
  'Soliman',
  'Sommer 1914',
  'Sonntagskinder',
  'Die Spanier in Peru oder Rollas Tod',
  'Die spanische Hochzeit',
  'Die spanische Hochzeit',
  'Spiegelmensch',
  'Die Spieldose',
  'Die Spielereien einer Kaiserin',
  'Spiel im Schloss',
  'Spiel ins Leben',
  'Das Spiel vom Fragen oder Die Reise zum sonoren Land',
  'Das Spiel vom Thomas-Kantor',
  'Spiel von den deutschen Ahnen',
  'Das Spiel von Erasmus Grasser',
  'Spiele der Macht',
  'Spiele um Geld',
  'Spieler',
  'Ein Sportstück',
  'Spur des dunklen Engels',
  'Staatsräson',
  'Stallerhof',
  'Stammheim',
  'Stan und Ollie in Deutschland',
  'Der standhafte Zinnsoldat',
  'Der starke Stamm',
  'Staschek oder Das Leben des Ovid',
  'Der staubige Regenbogen',
  'Stauffer-Bern',
  'Die St. Jakobsfahrt',
  'Die Stadt der Besessenen',
  'Stefan Fadinger',
  'Der Stein der Weisen',
  'Stein unter Steinen',
  'Steine im Weg',
  'Stella',
  'Der Stellvertreter',
  'Stempelbrüder',
  'Der sterbende Cato',
  'Die sterblichen Güter',
  'Sterntaler',
  'Stigma',
  'Stille Gäste',
  'Stille Nacht',
  'Stille Ronnie',
  'Stinkwut',
  'Stirb & Werde',
  'Strandgut',
  'Die Strandkinder',
  'Der stramme Max',
  'Die Straße nach Cavarcere',
  'Straßenecke',
  'Die Stricknadeln',
  'Der Strom',
  'Studentenkomödie oder Mit der Zeit werden wir fertig',
  'Das Stück mit dem Hammer',
  'Die Stühle des Herrn Szmil',
  'Ein Stündchen im Comptoir',
  'Stürme',
  'Stützpunkt Trufanowa',
  'Die Stunde, da wir voneinander nichts wußten',
  'Die Stunde der Antigone',
  'Die Stunde des Hauptmanns Grisel',
  'Die Stunde des Triumphes',
  'Der Stundenhändler',
  'Der Sturz des Apostels Paulus',
  'Stunde Null',
  'Sturm im Wasserglas',
  'Sturmgeselle Sokrates',
  'Die Südpolarexpedition des Kapitäns Scott',
  'Die Sündflut',
  'Sweet Death',
  'Tabula rasa',
  'Die Tage der Commune',
  'Tag für Tag',
  'Der Tag I',
  'Ein Tag mit Edward',
  'Der Tag mit der Frau mit den Blumen',
  'Tai Yang erwacht',
  'Das Tal des Lebens',
  'Der Talisman',
  'Der Talisman oder Die Schicksalsperücken',
  'Talk Show',
  'Der Tambour und sein Herr König',
  'Tango Sólo',
  'Tannhäuser',
  'Tantris der Narr',
  'Das tausendjährige Reich',
  'terra incognita',
  'Tersites',
  'Der Teufel',
  'Der Teufel stellt Monsieur Darcy ein Bein',
  'Des Teufels General',
  'Der Teufelskreis',
  'Der Theatermacher',
  'Theater',
  'Thomas Chatterton',
  'Die Tochter der Kathedrale',
  'Tomas Müntzer',
  'Die tote Tante',
  'Thomas Münzer',
  'Thomas Münzer. Der Mann mit der Regenbogenfahne',
  'Thymian und Drachentod',
  'Till Eulenspiegel',
  'Till Eulenspiegel',
  'Till bevor er hing',
  'Tobias Bundschuh',
  'Die Tochter Theoderichs',
  'Der Tochtermord, welchen Jephtha begangen hat',
  'Der Tod des Empedokles',
  'Der Tod des Tizian',
  'Tod eines Jägers',
  'Tod und Teufel (Wedekind)',
  'Tolkening',
  'Toller',
  'Der tollste Tag',
  'Toni Stürmer',
  'Top Dogs',
  'Torquato Tasso',
  'Der Tor und der Tod',
  'Der tote Tag',
  'Totenfloß',
  'Transportarbeiter Jakob Kuhn',
  'Der Traum ein Leben',
  'Ein treuer Diener seines Herrn',
  'Triki-Traki',
  'Trilogie des Wiedersehens',
  'Triptychon',
  'Tristram und Ysolt',
  'Der Tritschtratsch',
  'Triumph in tausend Jahren',
  'Trommeln in der Nacht',
  'Tropfen auf heiße Steine',
  'Trotzki in Coyoacan',
  'Trotzki im Exil',
  'Die Tür',
  'Turandot oder Der Kongreß der Weißwäscher',
  'Türkischer Halbmond',
  'Der Turm',
  'Der Turm',
  'Tyrannen',
  'U-Boot S4',
  'Über allen Gipfeln ist Ruh',
  'Über den Gartenzaun',
  'Über die Dörfer',
  'Überfürchtenichts',
  'Die Übergangsgesellschaft',
  'Überlebensgroß Herr Krott',
  'Der Überteufel',
  'Ugolino',
  'Die Uhr schlägt eins',
  'Die Uhren',
  'Ulla Winblad',
  'Ulrich, Fürst von Waldeck',
  'Ulrich von Lichtenstein',
  'Ulrike Maria Stuart',
  'Um ein bißchen Rauch',
  'Um neun an der Achterbahn',
  'Die Umsiedlerin oder Das Leben auf dem Lande',
  'Umwege',
  'Der Unbedeutende',
  'Unbefleckte Empfängnis',
  'Eine Unbekannte aus der Seine',
  'Der Unbelehrbare',
  'Der Unbestechliche',
  'Und Pippa tanzt!',
  'Unerwartete Rückkehr',
  'Die Unfruchtbaren',
  'Der Unglückselige Soldat und Vorwitzige Barbier',
  'Der Unmensch',
  'Unruhige Träume',
  'Der Unschuldige',
  'Die Unschuldige',
  'Unter der Gürtellinie',
  'Unterm Rock der Teufel',
  'Unterm Wind der Jahre',
  'Eine verfolgte Unschuld',
  'Die unvergnügte Seele',
  'Unverhofft oder Der Lotterbube',
  'Die Unvermählte',
  'Die Unvernünftigen sterben aus',
  'Urfaust',
  'Das Urteil',
  'Die Valentine',
  'Van Gogh',
  'Vanillikipferln',
  'Varieté',
  'Vasantasena',
  'Vatermord',
  'Der Vatermord',
  'Veland',
  'Verbotene Früchte (Der Schwarzkünstler)',
  'Der verbannte Amor oder Die argwöhnischen Eheleute',
  'Verfolgung',
  'Die Verfolgung und Ermordung Jean Paul Marats, dargestellt durch die Schauspielgruppe des Hospizes zu Charenton unter Anleitung des Herrn de Sade',
  'Die Verführung',
  'Der vergessene Tag',
  'Die verhängnisvolle Faschingsnacht',
  'Das Verhör von Habana',
  'Das verliebte Gespenst',
  'Das Verlöbnis',
  'Die verlorene Ehre der Katharina Blum',
  'Der verlorene Sohn',
  'Der Vermessungsdirigent',
  'Die verschleierte Frau',
  'Der Verschwender',
  'Die Verschwörer',
  'Die Verschwörung',
  'Die Verschwörung des Fiesco zu Genua',
  'Der verschwundene Mond',
  'Die Versicherung',
  'Die Verspätung',
  'Die Versuchung',
  'Die versunkene Glocke',
  'Der verwandelte Komödiant',
  'Die vier Musketiere',
  'Das vierte Gebot',
  'Der vierundzwanzigste Februar',
  'Das Volksbuch vom Herzog Ernst oder Der Held und sein Gefolge',
  'Verschwörung um Hannes',
  'Vertauschte Seelen',
  'Verwandlungen',
  'Vincenz oder die Freundin bedeutender Männer',
  'Vineta',
  'Virginia',
  'Volk in Not',
  'Vom Esau und Jacob',
  'Vom verfolgten David',
  'Vom verfolgten Lateiner',
  'Vom Werden der Vernunft oder Auf der Durchreise nach Petersburg',
  'Von Bergamo bis morgen früh',
  'Von dem Mensch, so unter die Mörder gefallen',
  'Von dem neapolitanischen Rebellen Masaniello',
  'Von der sizilianischen Argenis',
  'Von der verkehrten Welt',
  'Von Jacobs doppelter Heirat',
  'Von Riesen und Menschen',
  'Von Tobias und der Schwalbe',
  'Vor der Klagemauer',
  'Vor Sonnenaufgang',
  'Vor Sonnenuntergang',
  'Der Voyeur',
  'Waffen für Amerika',
  'Das Wagnis der Maria Diehl',
  'Wahn oder der Teufel in Boston',
  'Wahnschaffe',
  'Die wahre Geschichte des Ah Q oder Zwischen Hund und Wolf',
  'Das wahre Gesicht',
  'Waidmannsheil oder Schöne Grüße aus der Steiermark',
  'Wallenstein',
  'Walküre 44',
  'Wanda, Königin der Sarmaten',
  'Die Wandlung',
  'Wann kommt Ehrlicher?',
  'Warenhauskomödie',
  'Was heißt hier Volsinii?',
  'Was wäre, wenn -?',
  'Wasser für Canitoga',
  'Watussi oder Ein Stück für zwei Botschafter',
  'Die Weber',
  'Weekend im Paradies',
  'Weg',
  'Der Weg der Verheißung',
  'Der Weg des Gewaltigen',
  'Der Weg nach Füssen',
  'Wege übers Land',
  'Wege zu Rahel',
  'Weh dem, der lügt!',
  'Weh dem, der nicht lügt',
  'Das Weib des Soldaten',
  'Der Weibsteufel',
  'Weismann und Rotgesicht',
  'Weissagung',
  'Der weiße Fächer',
  'Der weiße Heiland',
  'Weitab Standard',
  'Das weite Land',
  'Weitere Aussichten',
  'Weißes Blut',
  'Wer andern eine Grube gräbt',
  'Wer durchs Laub geht …',
  'Wer weint um Juckenack?',
  'Der Werwolf',
  'Wessis in Weimar',
  'Der Wettlauf mit dem Schatten',
  'Der WG-Krieg',
  'Ein Wiedersehen',
  'Wie führe ich eine Ehe?',
  'Wie Tiere des Waldes',
  'Wieland',
  'Wiener Kripperl von 1919',
  'Wiener Totentanz',
  'Die wilde Rotte',
  'Der Wildfang',
  'Wildfeuer',
  'Wildwechsel',
  'Wilhelm, Prinz von Oranien',
  'Wilhelm Tell',
  'William Becher-Leben und Werk in Lindau',
  'Winterballade',
  'Winterreise',
  'Winterschlacht',
  'Die Wirklichkeit und was man dagegen tut',
  'Der Wirrwarr',
  'Wir sind schon weiter',
  'Wittek geht um',
  'Die Witwe',
  'Die Witwe Capet',
  'Ein Wohltäter',
  'Wo liegt Jena?',
  'Wolfszeit',
  'Wolkenkuckucksheim',
  'Woyzeck',
  'Wunder um Verdun',
  'Das Wunschkonzert',
  'Die Wupper',
  "Ein Yankee an König Artus' Hof",
  'Yorck',
  'Zaza',
  'Zeit der Schuldlosen',
  'Die Zeit und das Zimmer',
  'Die Zensur',
  'Der Zentaur',
  'Der zerbrochne Krug',
  'Zero',
  'Zero-Zero',
  'Der Zerrissene',
  'Zigeuner-Boxer',
  'Die Zimmerschlacht',
  'Zinnober',
  'Der Zögling von San Marco',
  'Zriny',
  'Zu ebener Erde und erster Stock oder Die Launen des Glücks',
  'Zum Frühstück zwei Männer',
  'Zur Zeit der Distelblüte',
  'Der Zusammenstoß',
  'Zwei Ärzte',
  'Zwei Engel steigen aus',
  'Zwei rechts, zwei links',
  'Zweimal Oliver',
  'Der Zweite',
  'Die Zwillinge',
  'Die Zwillingsschwester',
  'Zwölfeläuten',
  'Zwölftausend',
];

export default plays;
