---
name: 'Deploy: Beta'

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  AWS_LIGHTSAIL_SERVICE_NAME: kulturdaten-api-beta
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PORT: 3333
      HOST: 0.0.0.0
      NODE_ENV: beta
      APP_KEY: dOu9BlkA6mEqVbn6c_aRBONwtYjMfKzQ
      API_URL: http://localhost:3333
      APP_URL: http://localhost:3333
      DB_CONNECTION: mysql
      CACHE_VIEWS: false
      FROM_EMAIL: ${{ secrets.ENV_FROM_EMAIL }}
      SMTP_HOST: ${{ secrets.ENV_SMTP_HOST }}
      SMTP_PORT: ${{ secrets.ENV_SMTP_PORT }}
      SMTP_USERNAME: ${{ secrets.ENV_SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.ENV_SMTP_PASSWORD }}
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setting up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Installing Node.js packages
        run: npm install

      - name: Running tests
        run: |
          npm run lint

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Install AWS CLI
        run: ./scripts/install-aws-cli.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker Image
        run: ./scripts/build-and-push-docker-image.sh

      - name: Push and Deploy
        run: ./scripts/update-container-service.sh
